# 자연어처리 소개

인간의 언어를 컴퓨터와 같은 기계가 묘사할 수 있도록 연구하고 구현하는 분야

: 음성 - Text화 - 말뭉치 사전 기준 토큰화 - 입력벡터 - 딥러닝 모델 처리 - 출력벡터 - 말뭉치 사전 참조 Text 벡터화 - 음성화

# 사전준비 및 라이브러리 설치

In [ ]:
# Sentencepiece 라이브러리 설치
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 20.9 MB/s eta 0:00:00


In [ ]:
# 한글형태소 분석기
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 34.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 38.5 MB/s eta 0:00:00


# 1.음성과 Text의 상호변환

## 가.관련 라이브러리 설치 : gTTS, SpeechRecognition

텍스트를 음성으로 변환 라이브러리 : https://pypi.org/project/gTTS/

In [3]:
# text to speech(TTS 음성변환)를 위한 라이브러리, text to speech
!pip install gTTS

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


음성인식 라이브러리 : https://pypi.org/project/SpeechRecognition/

In [1]:
# speech to text(STT 음성인식) 처리를 위한 라이브러리
!pip3 install SpeechRecognition

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.8/32.8 MB 36.6 MB/s eta 0:00:00


## 나.Text를 음성으로 변환: TTS 기술

In [6]:
from gtts import gTTS
#text ="알았어 오늘 저녁 메뉴가 뭐야? 진성곱창구이로 하지? 찬이는 집에 있어? " #안녕하세요. 여러분! 자연어처리 너무 재미 있지요? .Amazon은 천 1995년 제프 베조스(Jeff Bezos)에 의해 설립된 이래, 삼십 여 년 동안 지속적으로성장하고 있는, 전자상거래 시장의 업계 1위 기업입니다. 꾸준하게 성장을 이루어오는 동안,Amazon은 이커머스 분야를 포함하여 클라우드 컴퓨팅, 리테일, 인공지능, 로봇 등과 같은"
text ="okay!"
# 
# 다양한 분야에 도전을 계속함으로써 성공을 이어오면서, 2018년 시가총액 1조 달러를 달성하기도 하는 수준으로 성장하고 있는 기업입니다.
# Amazon의 단순하고 모방하기 쉬운 비즈니스 모델은, 월마트, 이베이, 알리바바 등 온라인, 
# 오프라인 소매업체와 치열한 경쟁에 직면하고 있습니다. 또한 Amazon의 시장 지배적인 입 
# 지에 따른 정부의 규제(독점 금지, 불공정)로 인한 제약이 있을 수 있습니다. 하지만 Amazon 
# 은 강력한 브랜드 인지도와 평판, 광범위한 유통 네트워크 구축, 첨단 기술 기반의 다양한 서 
# 비스, 다양한 기술(벤처)에 대한 적극적 투자와 파트너십, 협업 등을 통하여 시장 경쟁력을 
# 강화하여 나가고 있습니다.
# 특히 Amazon이 추구하고 있는 장기적 안목을 가지고 혁신을 통하여 고객 만족을 위한 노 
# 력은 Amazon이 가지고 있는 강력한 발전 전략이 될 수 있을 것입니다. 최신의 컴퓨팅 기술 
# 을 적극적으로 활용하여 세계 최대 전자상거래 업체로서의 경쟁 우위를 유지하고 발전해왔 
# 으며, 클라우드 컴퓨팅, 인공지능, 빅데이터 등의 기술을 활용하여 고객 경험을 개선하고 고 
# 객 맞춤형 서비스를 제공함으로써 고객 만족도를 높이고 경쟁력을 강화하여 나가고 있습니 
# 다.
# 이러한 고객 중심의 문화, 혁신적인 기술에 대한 투자와 도입, 지속 가능한 비즈니스 모델 
# 도입과 친환경 전략, 공급망 및 물류 혁신은, Amazon이 최근의 글로벌 경기 침체로 인한 위 
# 기를 극복하고 앞으로 글로벌 시장에서 지속적인 성장을 이루어 낼 것으로 전망할 수 있습 
# 니다."

tts = gTTS(text=text, lang='ko')
tts.save("dinner_menu.mp3")

좌측 탐색기 폴더를 열고 hello.mp3파일을 다운로드 받아서 들어보세요!

## 다.음성을 Text로 변환 : STT 기술

In [ ]:
#음성을 wav파일로 변환

!ffmpeg -i hello_amazon.mp3 mykor.wav

ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --e

In [ ]:
#녹음 타일을 텍스트로 바꿔주기, speetch to text, 유료버전 많음, 모니터에 설치하면 나오는 음성을 텍스트로 변경가능
import speech_recognition as sr
r = sr.Recognizer()
harvard = sr.AudioFile("mykor.wav")
with harvard as source:
    audio = r.record(source)
print(r.recognize_google(audio, language='ko-KR'))

여러분 자연어처리 너무 재미있게 아마존 인공지능 로봇


# 2.말뭉치 사전 만들기 기초

말뭉치 사전 : 자연언어 연구를 위해 특정한 목적을 가지고 언어의 표본을 추출한 집합

Text를 수치화 시키는 방법은 말뭉치 사전을 만들고 그것을 기준으로 One-Hot Encoding과 BOW 방법이 있었으나 비효율 적이거나 정보의 유실이 있어 다른 방법을 모색

## 가.말뭉치 사전 만들기

In [ ]:
corpus = """나는 학교에 다니는 학생 입니다
나는 좋은 선생님 입니다
당신은 매우 좋은 선생님 입니다"""

In [ ]:
# 띄어쓰기 기준 토큰으로 분리 .split(), 중첩 제외하고
tokens = corpus.split()
words = list(dict.fromkeys(tokens))
words

['나는', '학교에', '다니는', '학생', '입니다', '좋은', '선생님', '당신은', '매우']

In [ ]:
# 각 단어에 고유한 번호 부여한 dictionary 생성
word_to_id = {'[PAD]': 0, '[UNK]': 1}  # [PAD]: 길이 맞추는 용도, [UNK]: 알 수 없는 token
for word in words:
    word_to_id[word] = len(word_to_id)
word_to_id

{'[PAD]': 0,
 '[UNK]': 1,
 '나는': 2,
 '학교에': 3,
 '다니는': 4,
 '학생': 5,
 '입니다': 6,
 '좋은': 7,
 '선생님': 8,
 '당신은': 9,
 '매우': 10}

In [ ]:
#튜플리스트화
word_to_id.items()

dict_items([('[PAD]', 0), ('[UNK]', 1), ('나는', 2), ('학교에', 3), ('다니는', 4), ('학생', 5), ('입니다', 6), ('좋은', 7), ('선생님', 8), ('당신은', 9), ('매우', 10)])

In [ ]:
word_to_id['선생님']

8

In [ ]:
# 고유한 번호로 부터 단어를 찾을 수 있는 dictionary 생성
id_to_word = {id:word for word, id in word_to_id.items()}
id_to_word

{0: '[PAD]',
 1: '[UNK]',
 2: '나는',
 3: '학교에',
 4: '다니는',
 5: '학생',
 6: '입니다',
 7: '좋은',
 8: '선생님',
 9: '당신은',
 10: '매우'}

In [ ]:
id_to_word[8]

'선생님'

In [ ]:
# 말뭉치 사전 : word_to_id
corpus_dic = word_to_id
# 말뭉치 인텍스를 기준으로한 사전
corpus_id = id_to_word
# corpus depth 는 길이
len(corpus_dic)

11

* 모든 단어를 포함하는 말뭉치 사전을 만들어서 각 단어에 인텍스를 부여
* 분석하고자 하는 문서를 사전의 고유한 인텍스로 수치화

## 나.One-Hot Encoding

하나의 토큰을 하나의 행벡터로 생성(단어수*사전수)

In [ ]:
text = '''나는 학교에 잘 다니는 학생 입니다
선생님 은 좋은 선생님 입니다'''

In [ ]:
# 줄바꿈 단위로 문장 분리,위의 문장은 이스케이프 \n이 있는 것임
sentences = text.split("\n")
sentences

['나는 학교에 잘 다니는 학생 입니다', '선생님 은 좋은 선생님 입니다']

In [ ]:
# 띄어쓰기 단위로 단어 분리
tokens = []
for sentence in sentences:
    tokens.append(sentence.split())
tokens

[['나는', '학교에', '잘', '다니는', '학생', '입니다'], ['선생님', '은', '좋은', '선생님', '입니다']]

In [ ]:
# tokens을 말뭉치사전의 고유 번호로 변경
token_ids = []
for line_token in tokens:
  line_ids = []
  for token in line_token:
    if token in words:
      line_ids.append(word_to_id[token])
    else:
      line_ids.append(word_to_id['[UNK]'])
  token_ids.append(line_ids)
print(tokens,'\n',token_ids)

[['나는', '학교에', '잘', '다니는', '학생', '입니다'], ['선생님', '은', '좋은', '선생님', '입니다']] 
 [[2, 3, 1, 4, 5, 6], [8, 1, 7, 8, 6]]


In [ ]:
# one hot encoding
one_hot_encodings = []
for line_token in token_ids:
    print(line_token)
    one_hot_line = []  # 한 줄을 표현하는 벡터
    for id in line_token:
        # print(id)
        one_hot = [0] * len(word_to_id)  # 모두 0인 벡터를 만듬
        # print(one_hot)
        one_hot[id] = 1  # 단어 id만 1로 변경
        print(id, one_hot)
        one_hot_line.append(one_hot)  # 단어를 라인에 추가
    print(one_hot_line)
    one_hot_encodings.append(one_hot_line)  # 라인을 전체 문서에 추가

[2, 3, 1, 4, 5, 6]
2 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
3 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
1 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
4 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
5 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
6 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]
[8, 1, 7, 8, 6]
8 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
1 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
7 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
8 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
6 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]


In [ ]:
# one-hot의 행렬의 구조는 문장수 * corpus_dic의 길이(열) * 토큰수(행)
one_hot_encodings

[[[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]]

In [ ]:
import numpy as np
# argmax는 max를 가지고 있는 index를 리턴, axis 개념 이해 필요
# shape 행렬수*열수*행수
a = np.arange(24).reshape(2,3,4)  # 총 0-23까지
print(a)
print(np.argmax(a, axis=0))   #0을 기준으로 최고 큰 숫자
print(np.argmax(a, axis=1))
print(np.argmax(a, axis=2))
print(np.argmax(a, axis=-1))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2 2 2 2]
 [2 2 2 2]]
[[3 3 3]
 [3 3 3]]
[[3 3 3]
 [3 3 3]]


In [ ]:
# help(np.argmax)

In [ ]:
# 행기준으로 one-hot을 찾아냄
import numpy as np
print(tokens[0])
np.argmax(np.array(one_hot_encodings[0]), axis=-1)

['나는', '학교에', '잘', '다니는', '학생', '입니다']


array([2, 3, 1, 4, 5, 6])

In [ ]:
# tf를 이용한 one-hot encoding, 조건: 문장들의 길이(rows)가 동일해야함 
import tensorflow as tf
# 열의 길이는 depth, corpus_dic 길이

tf_one_hot_encodings = tf.one_hot(indices=token_ids[0], depth=len(word_to_id))
tf_one_hot_encodings

<tf.Tensor: shape=(6, 11), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# 문장들의 길이가 rows = 6 되도록 pad를 추가
pad_ids = []
rows=6
for line in token_ids:
    line = line[:rows]
    line += [0] * (rows - len(line))
    pad_ids.append(line)
pad_ids

[[2, 3, 1, 4, 5, 6], [8, 1, 7, 8, 6, 0]]

In [ ]:
#기존 one-hot에서 마지막 행 pad가 추가된 one-hot
tf_one_hot_encodings = tf.one_hot(indices=pad_ids, depth=len(word_to_id))
tf_one_hot_encodings

<tf.Tensor: shape=(2, 6, 11), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
# [나는 학교에 잘 다니는 학생 입니다]의 one-hot encoding
import pandas as pd

df = pd.DataFrame(np.int8(tf_one_hot_encodings[1]), columns=corpus_dic.keys())
df

[PAD]  [UNK]  나는  학교에  다니는  학생  입니다  좋은  선생님  당신은  매우
0      0      0   0    0    0   0    0   0    1    0   0
1      0      1   0    0    0   0    0   0    0    0   0
2      0      0   0    0    0   0    0   1    0    0   0
3      0      0   0    0    0   0    0   0    1    0   0
4      0      0   0    0    0   0    1   0    0    0   0
5      1      0   0    0    0   0    0   0    0    0   0

## 다.BOW 생성

말뭉치 사전의 토큰 인덱스 위치에 토큰 출현 회수 누적, 순서 정보의 손실

In [ ]:
sentences

['나는 학교에 잘 다니는 학생 입니다', '선생님 은 좋은 선생님 입니다']

In [ ]:
# sentences의 one-hot으로부터 열 기준합계로 Bow 생성
sentence = np.sum(tf_one_hot_encodings, axis=1)
sentence

array([[0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 1., 1., 2., 0., 0.]], dtype=float32)

In [ ]:
# [나는 학교에 잘 다니는 학생 입니다, 선생님 은 좋은 선생님 입니다]의 BOW 표현
import pandas as pd
df = pd.DataFrame(np.int8(sentence), columns=corpus_dic.keys())
df

[PAD]  [UNK]  나는  학교에  다니는  학생  입니다  좋은  선생님  당신은  매우
0      0      1   1    1    1   1    1   0    0    0   0
1      1      1   0    0    0   0    1   1    2    0   0

# 3.다양한 형태의 토큰화

토큰화 : 일정한 입력단위로 분할

## 가.문자나 단어 단위 토큰화

In [ ]:
corpus

'나는 학교에 다니는 학생 입니다\n나는 좋은 선생님 입니다\n당신은 매우 좋은 선생님 입니다'

In [ ]:
# 문자단위로 나누기: list
print(list(corpus))

['나', '는', ' ', '학', '교', '에', ' ', '다', '니', '는', ' ', '학', '생', ' ', '입', '니', '다', '\n', '나', '는', ' ', '좋', '은', ' ', '선', '생', '님', ' ', '입', '니', '다', '\n', '당', '신', '은', ' ', '매', '우', ' ', '좋', '은', ' ', '선', '생', '님', ' ', '입', '니', '다']


In [ ]:
# space 기준 단어단위 나누기 : split
print(corpus.split())

['나는', '학교에', '다니는', '학생', '입니다', '나는', '좋은', '선생님', '입니다', '당신은', '매우', '좋은', '선생님', '입니다']


## 나.한글형태소 분석기를 이용한 토큰화

In [ ]:
import konlpy
komoran = konlpy.tag.Komoran()
komoran.morphs('아버지가방에들어가신다')

['아버지', '가방', '에', '들어가', '시', 'ㄴ다']

In [ ]:
print(komoran.morphs(corpus))

['나', '는', '학교', '에', '다니', '는', '학생', '이', 'ㅂ니다', '나', '는', '좋', '은', '선생님', '이', 'ㅂ니다', '당신', '은', '매우', '좋', '은', '선생님', '이', 'ㅂ니다']


In [ ]:
text = '홍길동 전화번호는 Kt 1234-5678번 입니까?'

In [ ]:
# 한글 형태소분석기 클래스 불러오기
from konlpy.tag import Hannanum, Komoran, Kkma, Okt

komoran = Komoran()
print(komoran.pos(text))

okt = Okt()
print(okt.pos(text))

[('홍길동', 'NNP'), ('전화번호', 'NNP'), ('는', 'JX'), ('Kt', 'SL'), ('1234', 'SN'), ('-', 'SW'), ('5678', 'SN'), ('번', 'NNB'), ('입', 'VV'), ('니까', 'EF'), ('?', 'SF')]
[('홍길동', 'Noun'), ('전화번호', 'Noun'), ('는', 'Josa'), ('Kt', 'Alpha'), ('1234-5678', 'Number'), ('번', 'Noun'), ('입', 'Noun'), ('니까', 'Josa'), ('?', 'Punctuation')]


In [ ]:
komoran.tagset

In [ ]:
# tagset 보기
print(komoran.tagset)

{'EC': '연결 어미', 'EF': '종결 어미', 'EP': '선어말어미', 'ETM': '관형형 전성 어미', 'ETN': '명사형 전성 어미', 'IC': '감탄사', 'JC': '접속 조사', 'JKB': '부사격 조사', 'JKC': '보격 조사', 'JKG': '관형격 조사', 'JKO': '목적격 조사', 'JKQ': '인용격 조사', 'JKS': '주격 조사', 'JKV': '호격 조사', 'JX': '보조사', 'MAG': '일반 부사', 'MAJ': '접속 부사', 'MM': '관형사', 'NA': '분석불능범주', 'NF': '명사추정범주', 'NNB': '의존 명사', 'NNG': '일반 명사', 'NNP': '고유 명사', 'NP': '대명사', 'NR': '수사', 'NV': '용언추정범주', 'SE': '줄임표', 'SF': '마침표, 물음표, 느낌표', 'SH': '한자', 'SL': '외국어', 'SN': '숫자', 'SO': '붙임표(물결,숨김,빠짐)', 'SP': '쉼표,가운뎃점,콜론,빗금', 'SS': '따옴표,괄호표,줄표', 'SW': '기타기호 (논리수학기호,화폐기호)', 'VA': '형용사', 'VCN': '부정 지정사', 'VCP': '긍정 지정사', 'VV': '동사', 'VX': '보조 용언', 'XPN': '체언 접두사', 'XR': '어근', 'XSA': '형용사 파생 접미사', 'XSN': '명사파생 접미사', 'XSV': '동사 파생 접미사'}


In [ ]:
# 형태소 분석
print(komoran.morphs(text))
print(okt.morphs(text))

['홍길동', '전화번호', '는', 'Kt', '1234', '-', '5678', '번', '입', '니까', '?']
['홍길동', '전화번호', '는', 'Kt', '1234-5678', '번', '입', '니까', '?']


In [ ]:
# 명사추출
print(komoran.nouns(text))
print(okt.nouns(text))

['홍길동', '전화번호', '번']
['홍길동', '전화번호', '번', '입']


## 다.토큰 다루는 여러가지 방법

In [ ]:
# 토큰 count
import collections
char_counter = collections.Counter()
char_counter.update(list(corpus))

In [ ]:
corpus

'나는 학교에 다니는 학생 입니다\n나는 좋은 선생님 입니다\n당신은 매우 좋은 선생님 입니다'

In [ ]:
print(char_counter)

Counter({' ': 11, '다': 4, '니': 4, '는': 3, '생': 3, '입': 3, '은': 3, '나': 2, '학': 2, '\n': 2, '좋': 2, '선': 2, '님': 2, '교': 1, '에': 1, '당': 1, '신': 1, '매': 1, '우': 1})


In [ ]:
# 유니크한 char 개수
print(len(char_counter))

19


In [ ]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [ ]:
# 빈도수가 많은 글자 10개 출력
most_freq = sorted(char_counter.items(), key=lambda item: item[1], reverse=True)
print(most_freq[:10])

[(' ', 11), ('다', 4), ('니', 4), ('는', 3), ('생', 3), ('입', 3), ('은', 3), ('나', 2), ('학', 2), ('\n', 2)]


In [ ]:
def get_key(item):
    return item[1]

most_freq = sorted(char_counter.items(), key=get_key, reverse=True)
print(most_freq[:10])

[(' ', 11), ('다', 4), ('니', 4), ('는', 3), ('생', 3), ('입', 3), ('은', 3), ('나', 2), ('학', 2), ('\n', 2)]


In [ ]:
# 빈도수가 적은 글자 10개 출력
least_freq = sorted(char_counter.items(), key=lambda item: item[1])
print(least_freq[:10])

[('교', 1), ('에', 1), ('당', 1), ('신', 1), ('매', 1), ('우', 1), ('나', 2), ('학', 2), ('\n', 2), ('좋', 2)]


In [ ]:
# 한글 문자를 참조 인덱스로 변환 함수 ord, 참조인덱스를 한글로 변환 chr 
print(ord('가'),ord('힣'), chr(44032), chr(44034))
# help(ord)

44032 55203 가 갂


In [ ]:
hangul = [chr(i) for i in range(ord('가'), ord('힣') + 1)]
len(hangul)

11172

In [ ]:
print(hangul[:100])

['가', '각', '갂', '갃', '간', '갅', '갆', '갇', '갈', '갉', '갊', '갋', '갌', '갍', '갎', '갏', '감', '갑', '값', '갓', '갔', '강', '갖', '갗', '갘', '같', '갚', '갛', '개', '객', '갞', '갟', '갠', '갡', '갢', '갣', '갤', '갥', '갦', '갧', '갨', '갩', '갪', '갫', '갬', '갭', '갮', '갯', '갰', '갱', '갲', '갳', '갴', '갵', '갶', '갷', '갸', '갹', '갺', '갻', '갼', '갽', '갾', '갿', '걀', '걁', '걂', '걃', '걄', '걅', '걆', '걇', '걈', '걉', '걊', '걋', '걌', '걍', '걎', '걏', '걐', '걑', '걒', '걓', '걔', '걕', '걖', '걗', '걘', '걙', '걚', '걛', '걜', '걝', '걞', '걟', '걠', '걡', '걢', '걣']


In [ ]:
print(hangul[-100:])

['흀', '흁', '흂', '흃', '흄', '흅', '흆', '흇', '흈', '흉', '흊', '흋', '흌', '흍', '흎', '흏', '흐', '흑', '흒', '흓', '흔', '흕', '흖', '흗', '흘', '흙', '흚', '흛', '흜', '흝', '흞', '흟', '흠', '흡', '흢', '흣', '흤', '흥', '흦', '흧', '흨', '흩', '흪', '흫', '희', '흭', '흮', '흯', '흰', '흱', '흲', '흳', '흴', '흵', '흶', '흷', '흸', '흹', '흺', '흻', '흼', '흽', '흾', '흿', '힀', '힁', '힂', '힃', '힄', '힅', '힆', '힇', '히', '힉', '힊', '힋', '힌', '힍', '힎', '힏', '힐', '힑', '힒', '힓', '힔', '힕', '힖', '힗', '힘', '힙', '힚', '힛', '힜', '힝', '힞', '힟', '힠', '힡', '힢', '힣']


In [ ]:
ord('ㄱ')

12593

In [ ]:
chr(12593)

'ㄱ'